# Generated by Django 6.0.3 on 2026-03-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_track_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='status',
            field=models.CharField(choices=[('DRF', 'Draft'), ('PSH', 'Published'), ('HIDE', 'Hidden')], default='DRF', max_length=4),
        ),
    ]
