# Generated by Django 6.0.3 on 2026-04-01 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_track_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tracks',
        ),
        migrations.CreateModel(
            name='TrackCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_courses', to='courses.track')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='track',
            name='courses',
            field=models.ManyToManyField(related_name='tracks', through='courses.TrackCourse', to='courses.course'),
        ),
        migrations.AddConstraint(
            model_name='trackcourse',
            constraint=models.UniqueConstraint(fields=('track', 'order'), name='unique_track_course_order'),
        ),
    ]
