# Generated by Django 6.0.3 on 2026-04-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_track_thumbnail_trackenrollment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trackcourse',
            constraint=models.UniqueConstraint(fields=('track', 'course'), name='unique_track_course'),
        ),
    ]
