# Generated by Django 6.0.3 on 2026-04-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_trackcourse_unique_track_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='description',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='thumbnail',
            field=models.ImageField(default=3, upload_to='courses/lessons/thumbnails/'),
            preserve_default=False,
        ),
    ]
