# Generated by Django 6.0.3 on 2026-04-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_coursecontent_description_coursecontent_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackenrollment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackenrollment',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackenrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
