# Generated by Django 6.0.3 on 2026-03-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STU', 'Student'), ('INS', 'Instructor')], default='STU', max_length=3),
        ),
    ]
